version: '3.4'

services:
  app: 
    image: daviuz/basic-rails7:latest
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development

volumes:
  gem_cache:
